config/routes.rb
Rails.application.routes.draw do
  devise_for :incharges
  resources :items
	root 'home#index'
	get 'home/about' => 'home#about'
	get 'items/:id/complain' => 'items#complain'
	patch 'items/:id/complain/:id' => 'items#cupdate'
	patch 'items/complain/resolved/:id' => 'items#resolved'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/incharge.rb
class Incharge < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :items
end

app/models/item.rb
require 'csv'
class Item < ApplicationRecord
	belongs_to :incharge
	validates :item_name, :model_number, :installation_date, :make, :status, :warranty, presence: true

	def self.to_csv
		# attributes = %w{ name e_number m_number make lab_location date_of_installation current_status }
		CSV.generate do |csv|
			csv << column_names

			all.each do |item|
				if item.approved==true
					csv << item.attributes.values_at(*column_names)
				end
			end
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html
      format.csv{ send_data @items.to_csv }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    item = Item.find(params[:id])
    if current_incharge.admin?
      if item.approved == false
        item.update_attribute(:approved, 'true')
        redirect_to "/items"
      else
        item.update_attribute(:approved, 'false')
        redirect_to "/items"
      end
    end
    
    if current_incharge.user == false
      if item.complaint==true
        item.update_attribute(:complaint, 'false')
        item.update_attribute(:status, 'Working')
        item.update_attribute(:description, 'NA')
      end
    else
      if item.update(item_params)
        redirect_to "/items"
      else
        flash[:errors]=item.errors.full_messages
        redirect_to "/items/<%= @item.id %>/edit"
      end
    end



    if current_incharge.admin == false && current_incharge.user == false
       respond_to do |format|
         if @item.update(item_params)
          format.html { redirect_to "/items", notice: 'Item was successfully updated.' }
           format.json { render :show, status: :ok, location: @item }
         else
           format.html { render :edit }
           format.json { render json: item.errors, status: :unprocessable_entity }
         end
       end
    end   
  end
  

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def complain
    @item = Item.find(params[:id])
  end

  def cupdate
    item = Item.find(params[:id])
    if current_incharge.user?
      if item.complaint == false
        item.update_attribute(:complaint, 'true')
        item.update_attribute(:status, 'Not Working')
        
      else
        item.update_attribute(:complaint, 'false')
        item.update_attribute(:status, 'Working')
    
      end      
    end 
    if item.update(item_params)
      redirect_to "/items"
    else
      flash[:errors]=item.errors.full_messages
      redirect_to "/items/<%= @item.id %>/edit"
    end
  end

  def resolved
    item = Item.find(params[:id])
    item.update_attribute(:complaint, 'false')
    item.update_attribute(:status, 'Working')
    item.update_attribute(:description, 'NA')       
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:item_name, :model_number, :make, :lab_name, :installation_date, :typeofpurchase, :warranty, :status, :incharge_id, :approved, :description, :complaint)
    end

    def complain_params
      params.permit(:description)
    end
      
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" >ITS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if incharge_signed_in? %>
  		<li class="nav-item">
          <%= link_to "Edit Profile", edit_incharge_registration_path, class:"nav-link active"  %>
  		</li>
  		<li class="nav-item">
          <%= link_to "Sign Out", destroy_incharge_session_path, method: :delete, class:"nav-link active"  %>
  		</li>
      <% if current_incharge.user==false && current_incharge.admin==false %>
        <li class="nav-item">
          <%= link_to "Add Item", new_item_path, class:"nav-link active"  %>
  		</li>
      <%end%>
  		<li class="nav-item">
          <%= link_to "Show Items", items_path, class:"nav-link active"  %>
  		</li>
  		<% else %> 
        <li class="nav-item">
          <%= link_to "Home", root_path, class:"nav-link active"  %>
        </li>
        <li class="nav-item">
          <%= link_to "About Us", home_about_path, class:"nav-link active"  %>
        </li>
		  </ul>

      <ul>
  		<li class="nav-item">
          <u><%= link_to "LOGIN", new_incharge_session_path, class:"btn btn-secondary" %></u>
  		</li>
  		<% end %>
      </ul>
      
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<html>
<head>
</head>
<body >
<h1>About Us</h1>
<P>Inventory Tracking System is a management system
for Computer Science and Engineering Department which will keep track of all the
Equipments(Computers, Printers, ACs, etc) listed by lab in-charge of different labs.The
system will be easily accessed by Administrators, Lab-Faculty and Students.Students can raised complain incase equipment stop working.</P>
<p>Lab-Faculties can add new equipment and then get approved by Administrator to view in the inventory.</p>
<center><%= image_tag ("logos/its.jpg") %></center>

<br></br>
<h2> Developed by:</h2>

<p>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;1) BALE ROHIT RAVINDAR</p>
<p>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;2) BHANU PRATAP VERMA</p>
<p>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;3) DEVESH RAO</p>
<p>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;4) DIROJIT KHERSA</p>
</body>
</html>

app/views/home/index.html.erb
	<% if incharge_signed_in? %>
		<div class = "container">
			<h1>Welcome to </h1><br><br>
			<u><h1>INVENTORY TRACKING SYSTEM</h1></u><br><br>
		 	
		 </div>	

	<% else %>

		<center>
		<br><br><br><%= image_tag ("logos/nitc.png") %><br><br><br>
		<u><h1>INVENTORY TRACKING SYSTEM</h1></u>
		</center>

	<% end %>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field form-group">
    <%= form.label :item_name %>
    <%= form.text_field :item_name, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :model_number %>
    <%= form.text_field :model_number, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :make %>
    <%= form.text_field :make, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :lab_name %>
    <%= form.text_field :lab_name, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :installation_date %>
    <%= form.date_select :installation_date, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :typeofpurchase %>
    <%= form.text_field :typeofpurchase, class:"form-control" %>
  </div>


  <div class="field form-group">
    <%= form.label :warranty %>
    <%= form.date_select :warranty, class:"datepicker" %>
  </div>

  <div class="field form-group">
    <%= form.label :status %>
    <%= form.text_field :status, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.number_field :incharge_id, id: :item_incharge_id, value: current_incharge.id, class:"form-control", type: :hidden %>
  </div>
  <div class="actions">
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/items/complain.html.erb
<% if current_incharge.user? %>
<h1> File Complaint </h1>
<form action="complain/<%= @item.id %>" method="post">
	<input type="hidden" name="_method" value="patch">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<div class="form-group">
		<label>Description:</label>
		<input type="text" name="item[description]" value="<%= @item.description %>" class="form-control">
	</div>
	<div class="form-group"> 
	<input type="submit" value="File Complaint" class="btn btn-dark">
	</div>
</form>

<% else %>

<h1> Report Complaint Status </h1>
<form action="complain/<%= @item.id %>" method="post">
	<input type="hidden" name="_method" value="patch">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<div class="form-group">
		<label>Description:</label>
		<input type="text" name="item[description]" value="<%= @item.description %>" class="form-control">
	</div>
	<div class="form-group"> 
	<input type="submit" value="Update" class="btn btn-dark">
	</div>
</form>

<% end %>

app/views/items/edit.html.erb
<% if incharge_signed_in? %>
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item, class:"btn btn-secondary" %> |
<%= link_to 'Back', items_path, class:"btn btn-secondary" %>
<% else %>
	<%= render 'layouts/static_landing_page' %>
<% end %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table class="table table-hover">
  <thead class="table-dark">
    <tr>
      <th>Item name</th>
      <th>Model number</th>
      <th>Make</th>
      <th>Lab</th>
      <th>Installation date</th>
      <th>Type of Purchase</th>
      <th>Warranty</th>
      <th>Status</th>
      <th>Complaint Description</th>
      <!-- <th>Incharge ID</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if current_incharge.user? %>
      <% @items.each do |item| %>
       <% if item.approved? %>
        <tr>
          <td><%= item.item_name %></td>
          <td><%= item.model_number %></td>
          <td><%= item.make %></td>
          <td><%= item.lab_name %></td>
          <td><%= item.installation_date %></td>
          <td><%= item.typeofpurchase%></td>
          <td><%= item.warranty %></td>
          <td><%= item.status %></td>
          <% if item.complaint? %>
          <td class="text-danger"><%= item.description %></td>
          <% else %>
          <td><%= item.description %></td>
          <% end %>
          <!-- <td><%= item.incharge.email %></td> -->
          <% if item.complaint == false %>
          <td><a href="items/<%= item.id %>/complain" class="btn btn-dark">File Complaint</a></td>
          <% else %>
            <td class="text-danger"><strong>Complaint filed</strong></td>
          <% end %>

        </tr>
        <% end %>
      <% end %>
    <% end %>
    <% if current_incharge.admin? %>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.item_name %></td>
        <td><%= item.model_number %></td>
        <td><%= item.make %></td>
        <td><%= item.lab_name %></td>
        <td><%= item.installation_date %></td>
        <td><%= item.typeofpurchase%></td>
        <td><%= item.warranty %></td>
        <td><%= item.status %></td>
        <% if item.complaint? %>
        <td class="text-danger"><%= item.description %></td>
        <% else %>
        <td><%= item.description %></td>
        <% end %>
        <!-- <td><%= item.incharge.email %></td> -->
        <% if item.approved == false %>
        <td><%= link_to 'Approve', item, method: :Patch, class:"btn btn-dark" %></td>
        <% else %>
        <% if item.approved == true %>
        <td><%= link_to 'Disapprove', item, method: :Patch, data: { confirm: 'Are you sure?' }, class:"btn btn-dark"%></td>
        <% end %>
        <% end %>
      </tr>
      <% end %>
    <% else %>
    <% @items.each do |item| %>
    <% if current_incharge == item.incharge %>
      <tr>
        <td><%= item.item_name %></td>
        <td><%= item.model_number %></td>
        <td><%= item.make %></td>
        <td><%= item.lab_name %></td>
        <td><%= item.installation_date %></td>
        <td><%= item.typeofpurchase%></td>
        <td><%= item.warranty %></td>
        <td><%= item.status %></td>
        <% if item.complaint? %>
        <td class="text-danger"><%= item.description %></td>
        <% else %>
        <td><%= item.description %></td>
        <% end %>

        <!-- <td><%= item.incharge.email %></td> -->
        <td><%= link_to 'Show', item, class:"btn btn-dark" %></td>
        <td><%= link_to 'Edit', edit_item_path(item), class:"btn btn-dark" %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-dark"%></td>
        <% if item.complaint == true %>
          <td><a href="items/<%= item.id %>/complain" class="btn btn-dark">Resolve Complaint</a></td>
            <%= item.update_attribute(:status, 'Working') %>
            <%= item.update_attribute(:complaint, false) %>
          <% else %>
          <td class="text-danger"><strong>No Complaints</strong></td>
        <% end %>
      </tr>
      <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<% if current_incharge.admin? %>
<%= link_to "Generate Approved List", "items.csv", class: "btn btn-primary"%>
<% end %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>
<br>
<%= link_to 'Back', items_path, class:"btn btn-dark" %>

app/views/items/show.html.erb
<% if incharge_signed_in? %>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<div class="jumbotron m-3">
  <h1 class="display-4"> <%= @item.item_name %> (<%= @item.make %>  <%= @item.model_number %>)</h1>
  <p class="lead"><strong>Installation date:- </strong> <%= @item.installation_date %></p>
  <p class="lead"><strong>Type of Purchase:- </strong> <%= @item.typeofpurchase %></p>
  <p class="lead"><strong>Lab Name:- </strong> <%= @item.lab_name %></p>
  <p class="lead"><strong>Warranty Expires on:- </strong> <%= @item.warranty %></p>
  <% if @item.status == "Working" %>
    <p class="lead"><strong><%= @item.item_name %> is Working fine</strong></p>
  <% else %>
    <p class="lead"><strong><%= @item.item_name %> is not Working</strong></p>
  <% end %>
  <hr class="my-4">
</div>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

<p id="notice"><%= notice %></p>
<%= link_to 'Edit', edit_item_path(@item), class:"btn btn-secondary" %> 
<%= link_to 'Back', items_path, class:"btn btn-secondary" %>
<% else %>
	<%= render 'layouts/static_landing_page' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <title>Inventory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
      <%= render 'home/header' %>
      <div class="container">
        <br>
        <%= yield %>
      </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>